version: '3'

services:
  api:
    image: continuumio/miniconda3
    ports:
      - "8001:8001"
    volumes:
      - ./segment_geospatial_api:/app
    working_dir: /app
    environment:
      - MODEL_PATH=/app/models
      - PYTHONPATH=/app
    command: >
      bash -c "
      conda env create -f environment.yml || conda env update -f environment.yml &&
      source /opt/conda/etc/profile.d/conda.sh &&
      conda activate geo_app_env &&
      uvicorn app.main:app --host 0.0.0.0 --port 8001" 