version: '3.8'

services:
  api:
    build:
      context: ./segment_geospatial_api
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - PYTHONPATH=/app

  web:
    build:
      context: ./segment_geospatial_frontend
      dockerfile: Dockerfile  # 注意这里使用生产版本的Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://api:8001
    depends_on:
      - api 