version: '3.8'

services:
  api:
    build:
      context: ./segment_geospatial_api
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./segment_geospatial_api:/app
    environment:
      - MODEL_PATH=/app/models
      - PYTHONPATH=/app
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G

  web:
    build:
      context: ./segment_geospatial_frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - api

volumes:
  conda_env: 