version: '3.8'

services:
  api:
    build:
      context: ./segment_geospatial_api
      dockerfile: Dockerfile.gpu  # We'll need to create this for API with GPU support
    ports:
      - "8001:8001"
    environment:
      - PYTHONPATH=/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped

networks:
  default:
    driver: bridge