services:
  streamlit:
    image: continuumio/miniconda3
    ports:
      - "8000:8000"
    volumes:
      - ./segment_geospatial_streamlit:/app
    working_dir: /app
    environment:
      - API_URL=http://api:8001
    command: >
      bash -c "
      conda env create -f environment.yml || conda env update -f environment.yml &&
      source /opt/conda/etc/profile.d/conda.sh &&
      conda activate geo_map_env &&
      streamlit run app.py --server.port 8000 --server.address 0.0.0.0" 