name: geo
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - segment-geospatial
  - groundingdino-py
  - segment-anything-fast
  - pydantic
  - fastapi
  - uvicorn
  - loguru
  - pytorch
  - geoai
  - pip
  - pip:
    - python-multipart>=0.0.5
    - pydantic_settings