name: geo_app_env
channels:
  - conda-forge
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.11
  - gdal
  - samgeo
  - pydantic
  - fastapi
  - uvicorn
  - loguru
  - typing_extensions
  - pip
  - pip:
    - groundingdino-py
    - torch
    - torchvision
    - python-multipart>=0.0.5
    - pydantic_settings
