name: geo_app_test_env
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.11
  - gdal
  - segment-geospatial
  - pycocotools
  - pytorch::pytorch
  - pytorch::torchvision
  - fastapi>=0.79.0,<0.100.0
  - pydantic=1.10.12
  - uvicorn>=0.18.2
  - loguru>=0.6.0
  - typing_extensions>=3.10.0
  - python-multipart>=0.0.5
  - pytest>=7.0.0
  - pytest-asyncio>=0.18.0
  - pytest-cov>=4.1.0
  - httpx>=0.23.0
  - black>=23.0.0
  - flake8>=6.0.0
  - mypy>=1.0.0
  - pip
  - pip:
    - groundingdino-py
    - pydantic-settings<2.0.0